name: CI/CD Filters

on:
  push:
    branches:
      - master
      - development
      - "feature/*"


    tags:
      - "v*.*.*"

    paths:
      - 'src/**'

  pull_request:
    types: [opened]

jobs:
  run-job-filters:
    runs-on: ubuntu-latest

    steps:
      - name: Log date
        run: echo date
      
      
  

      
