name: Pull request review Event

on: pull_request_review

jobs: 
  build: 
    runs-on: ubuntu-latest


    steps:
    - name: Display "Pull request review event"
      run: echo "Pull request review event"
